apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanicaos-api
  namespace: mecanicaos
  labels:
    app: mecanicaos-api
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: mecanicaos-api
  template:
    metadata:
      labels:
        app: mecanicaos-api
    spec:
      containers:
        - name: mecanicaos-api
          image: ${docker_image}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-configmap
            - secretRef:
                name: api-secret
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
