apiVersion: v1
kind: Service
metadata:
  name: mecanicaos-service
  namespace: mecanicaos
  labels:
    app: mecanicaos-api
  annotations:
    # Esta anotação garante que um Network Load Balancer (NLB) seja criado,
    # o que é necessário para a integração com o VPC Link do API Gateway.
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: mecanicaos-api
  type: LoadBalancer # Alterado de volta para LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
