apiVersion: v1
kind: Service
metadata:
  name: mecanicaos-service
  namespace: mecanicaos
  labels:
    app: mecanicaos-api
spec:
  selector:
    app: mecanicaos-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80