apiVersion: v1
kind: Service
metadata:
  name: mecanicaos-service
  namespace: mecanicaos
  labels:
    app: mecanicaos-api
  annotations:
    # Anotacoes especificas da AWS para o Load Balancer Controller
    # Garante que o Health Check do ELB use a rota /health da aplicacao.
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/#healthcheck
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    # --- Parametros Otimizados para Health Check ---
    # Intervalo entre checks: 30 segundos.
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    # Timeout do check: 5 segundos.
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    # Thresholds: 2 checks bem-sucedidos para considerar saudavel, 2 falhas para insalubre.
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
spec:
  selector:
    app: mecanicaos-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80